/* 
// This file is subject to the terms and conditions defined in
// file 'LICENSE.md', which is part of this source code package.
*/

#include "bridge/pins.h"

const pin_size_t variantPinCount = 37;

PinState variantPinStates[variantPinCount] = {
    {D0, 0, NULL, /*NULL, NULL, NULL,*/ NULL},    // ACCELL_INT2/2
    {D1, 1, NULL, /*NULL, NULL, NULL,*/ NULL},    // GPIO 1
    //{D2, 2, NULL, /*NULL, NULL, NULL,*/ NULL},  // NOT CONNECTED
    {D3, 3, NULL, /*NULL, NULL, NULL,*/ NULL},    // GPIO 3
    {D4, 4, NULL, /*NULL, NULL, NULL,*/ NULL},    // GPIO4/CAMERA_Y4  / 2
    {D5, 5, NULL, /*NULL, NULL, NULL,*/ NULL},    // GPIO5/CAMERA_Y3  / 2
    {D6, 6, NULL, /*NULL, NULL, NULL,*/ NULL},    // GPIO6/CAMERA_y0  / 2
    {D7, 7, NULL, /*NULL, NULL, NULL,*/ NULL},    // GPIO7/CAMERA_XCLK/ 2
    {D8, 8, NULL, /*NULL, NULL, NULL,*/ NULL},    // GPIO8/CAMERA_Y1  / 2
    {D9, 9, NULL, /*NULL, NULL, NULL,*/ NULL},    // GPIO9/CAMERA_Y2  / 2
    {D10, 10, NULL, /*NULL, NULL, NULL,*/ NULL},  // GPIO10/CAMERA_DVDD_EN /2
    {D11, 11, NULL, /*NULL, NULL, NULL,*/ NULL},  // GPIO11/MICO / 2
    {D12, 12, NULL, /*NULL, NULL, NULL,*/ NULL},  // GPIO12/CAMERA_VSYNC/2
    {D13, 13, NULL, /*NULL, NULL, NULL,*/ NULL},  // GPIO13/CAMERA_PWON /2
    {D14, 14, NULL, /*NULL, NULL, NULL,*/ NULL},  // GPIO14/USER_BUTTON
    {D15, 15, NULL, /*NULL, NULL, NULL,*/ NULL},  // GPIO15/CAMERA/RESET/2
    //{D16, 16, NULL, /*NULL, NULL, NULL,*/ NULL},// NOT CONNECTED
    {D17, 17, NULL, /*NULL, NULL, NULL,*/ NULL},  // GPIO17/ACCEL_INT1/2
    //{D18, 18, NULL, /*NULL, NULL, NULL,*/ NULL},// NOT CONNECTED
    //{D19, 19, NULL, /*NULL, NULL, NULL,*/ NULL},// NOT CONNECTED
    {D20, 20, NULL, /*NULL, NULL, NULL,*/ NULL},  // GPIO20/SWDCK
    {D21, 21, NULL, /*NULL, NULL, NULL,*/ NULL},  // GPIO21/SWDIO
    {D22, 22, NULL, /*NULL, NULL, NULL,*/ NULL},  // GPIO22/CAMERA_Y5/2
    {D23, 23, NULL, /*NULL, NULL, NULL,*/ NULL},  // GPIO23/CAMERA_PCLK/2
    {D24, 24, NULL, /*NULL, NULL, NULL,*/ NULL},  // GPIO24/CAMERA_Y6/2
    {D25, 25, NULL, /*NULL, NULL, NULL,*/ NULL},  // GPIO25/I2C_SDA_CAMERA/2
    {D26, 26, NULL, /*NULL, NULL, NULL,*/ NULL},  // GPIO26/CAMERA_HREF/2
    {D27, 27, NULL, /*NULL, NULL, NULL,*/ NULL},  // GPIO27/I2C_SCL_CAMERA/2
    {D28, 28, NULL, /*NULL, NULL, NULL,*/ NULL},  // GPIO28/CAMERA_Y7/2
    {D29, 29, NULL, /*NULL, NULL, NULL,*/ NULL},  // GPIO29/MIC1/2
    //{D30, 30, NULL, /*NULL, NULL, NULL,*/ NULL},// NOT CONNECTED
    //{D31, 31, NULL, /*NULL, NULL, NULL,*/ NULL},// NOT CONNECTED
    //{D32, 32, NULL, /*NULL, NULL, NULL,*/ NULL},// NOT CONNECTED
    {D33, 33, NULL, /*NULL, NULL, NULL,*/ NULL},  // GPIO33/SWO
    //{D34, 34, NULL, /*NULL, NULL, NULL,*/ NULL},// NOT CONNECTED
    //{D35, 35, NULL, /*NULL, NULL, NULL,*/ NULL},// NOT CONNECTED
    {D36, 36, NULL, /*NULL, NULL, NULL,*/ NULL},  // GPIO36_J3_4
    {D37, 37, NULL, /*NULL, NULL, NULL,*/ NULL},  // GPIO37_LED_BLUE
    {D38, 38, NULL, /*NULL, NULL, NULL,*/ NULL},  // GPIO38_J3_3
    {D39, 39, NULL, /*NULL, NULL, NULL,*/ NULL},  // GPIO39_QWICC_SCk
    {D40, 40, NULL, /*NULL, NULL, NULL,*/ NULL},  // GPIO40_QWICC_SDA
    //{D41, 41, NULL, /*NULL, NULL, NULL,*/ NULL},// NOT CONNECTED
    {D42, 42, NULL, /*NULL, NULL, NULL,*/ NULL},  // GPIO42/I2C_SCLK/2
    {D43, 43, NULL, /*NULL, NULL, NULL,*/ NULL},  // GPIO43/I2C_SDA/2
    {D44, 44, NULL, /*NULL, NULL, NULL,*/ NULL},  // GPIO44/LED_GREEN
    //{D45, 45, NULL, /*NULL, NULL, NULL,*/ NULL},// NOT CONNECTED
    {D46, 46, NULL, /*NULL, NULL, NULL,*/ NULL},  // GPIO46/ LED_RED
    {D47, 47, NULL, /*NULL, NULL, NULL,*/ NULL},  // GPIO46/ LED_YELLOW
};
